#version 430 core
layout(local_size_x = 16, local_size_y = 16) in;
layout(r32ui, binding = 0) uniform uimage2D img_inR;
layout(r32ui, binding = 1) uniform uimage2D img_inG;
layout(r32ui, binding = 2) uniform uimage2D img_inB;

layout(r32ui, binding = 3) uniform uimage2D img_outR;
layout(r32ui, binding = 4) uniform uimage2D img_outG;
layout(r32ui, binding = 5) uniform uimage2D img_outB;


void main() {
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    if (p.x >= imageSize(img_inR).x || p.y >= imageSize(img_inR).y) return;
    float sum = 0.0;
    float kk = 0.7;
    for (int dy = -4; dy <= 4; ++dy)
        for (int dx = -4; dx <= 4; ++dx) {
            float w = exp(-float(dx*dx + dy*dy) * kk);
            sum += float(imageLoad(img_inR, p + ivec2(dx,dy)).r) * w;
        }
    imageAtomicAdd(img_outR, p, uint(sum));
    sum = 0.0f;
    for (int dy = -4; dy <= 4; ++dy)
        for (int dx = -4; dx <= 4; ++dx) {
            float w = exp(-float(dx*dx + dy*dy) * kk);
            sum += float(imageLoad(img_inG, p + ivec2(dx,dy)).r) * w;
        }
    imageAtomicAdd(img_outG, p, uint(sum));
    sum = 0.0f;
    for (int dy = -4; dy <= 4; ++dy)
        for (int dx = -4; dx <= 4; ++dx) {
            float w = exp(-float(dx*dx + dy*dy) * kk);
            sum += float(imageLoad(img_inB, p + ivec2(dx,dy)).r) * w;
        }
    imageAtomicAdd(img_outB, p, uint(sum));
}